version: '3'

services:
  web_visualization:
    build:
      context: ./covid_19/
      dockerfile: Dockerfile
    ports:
      - ${COVID_APP_PUBLISHED_PORT}:8050
    env_file:
      - ./.env
    environment:
      - LAUNCHED_FROM_DOCKER_COMPOSE=True
