version: '3'

services:
  web_visualization:
    build:
      context: ./covid_19/
      dockerfile: Dockerfile
      args:
        APP_EXPOSED_PORT: ${COVID_APP_CONTAINER_EXPOSED_PORT}
    ports:
      - ${COVID_APP_PUBLISHED_PORT}:${COVID_APP_CONTAINER_EXPOSED_PORT}
    env_file:
      - ./.env
